server:
  port: 7002
spring:
  application:
    name: jooq
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://test-polarm-global-01-sh2e.taimei.com:3306/hsj_test
    username: pvuser
    password: pv@TM123
    name: hsj_test
logging:
  config: classpath:logback.xml
